#!/bin/bash

echo "1. Start nano redactor"
echo "2. Start vi redactor"
echo "3. Start links"
echo "4. Exit"

let command 
read "command"
case $command in 
1 )
nano
;;
2 )
vi
;;
3 ) 
links
;;
4 )
exit 
;;
esac
